# Generated by Django 5.2.7 on 2025-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='illegal_logging_classification',
            field=models.CharField(blank=True, choices=[('penebangan_liar', 'Penebangan Liar'), ('tidak_penebangan_liar', 'Tidak Penebangan Liar')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='public_fire_classification',
            field=models.CharField(blank=True, choices=[('fire', 'Fire'), ('no_fire', 'No Fire')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='trash_classification',
            field=models.CharField(blank=True, choices=[('banyak_sampah', 'Banyak Sampah'), ('sedikit_sampah', 'Sedikit Sampah')], max_length=50, null=True),
        ),
    ]
