# Generated by Django 5.2.7 on 2025-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report_illegal_logging_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
